rf:
  criterion:
  - squared_error
  - absolute_error
  max_depth:
  - 2 
  - 5 
  - 10
  - 20
  - null
  max_features:
  - auto
  - sqrt
  - log2
  max_samples:
  - 1.0
  - .9
  - .8
  - .7
  - .6
  min_samples_leaf:
  - 1
  - 2
  - 5
  - 10
  - 15
  - 20
  min_samples_split:
  - 2
  - 5
  - 10
  - 15
  - 20
  n_estimators:
  - 100
  - 250 
  - 500
  - 1000
  oob_score:
  - true
