---
output: html_document2
editor_options: 
  chunk_output_type: console
---

# Appendix {-#appendix}

Some proofs of the mathematical concepts used in the study are derived, specifically related to duration analysis.  

## Hazard function {-}

\begin{equation}    
  \begin{aligned}
  \lambda(t) & = \lim_{\Delta t \to 0} \frac{P\big[t \leq T < t + \Delta t | T \geq t \big]}{\Delta t} \\\\
  & = \lim_{\Delta t \to 0} \frac{P\big[t \leq T < t + \Delta t \big] / P\big[T \geq t  \big]}{\Delta t} \\\\
  & = \lim_{\Delta t \to 0} \frac{\big(F(t+\Delta t)-F(t)\big) / \Delta t}{S(t)} \\\\
  & = \frac{\text{d} F(t) / \text{d} t}{S(t)} \\\\
  & = \frac{f(t)}{S(t)} \\\\
  \lambda(t) & = \frac{-\text{d} \ln \big(S(t)\big)}{\text{d} t}
  \end{aligned}
  (\#eq:hazfunproof)
\end{equation}


## Link between cumulative hazard and survivor functions {-}

\begin{equation}
  \begin{aligned}
       & \Lambda(t) = \int_{0}^{t} \lambda(s)ds \\\\
  \iff & \Lambda(t) = \int_{0}^{t} \frac{f(s)}{S(s)}ds \\\\
  \iff & \Lambda(t) = -\ln \big(S(t)\big) \\\\
  \iff & S(t) = \exp \big(-\Lambda(t)\big)
  \end{aligned}
  (\#eq:linksurvcumhaz)
\end{equation}

```{r eval=FALSE}
# **Hazard function in AFT models**

# \begin{equation}
# \begin{aligned}
# & \ln t = \pmb{x}^{'}\beta + u \\\\
# \iff & t = \text{e}^{\pmb{x}^{'}\beta + u} \\\\
# \iff & t = \text{e}^{\pmb{x}^{'}\beta} v \ \text{with } v = e^u \\\\
# \iff & \lambda(t|\pmb{x}) = \lambda_0 \big(t \text{e}^{-\pmb{x'}\beta} \big) \text{e}^{\pmb{x'}\beta} \ \text{with } v = t \text{e}^{-\pmb{x'}\beta}
# \end{aligned}
# (\#eq:hazaftproof)
# \end{equation}
```

## Contribution to the partial likelihood function in PH models {-}

\begin{equation}
\begin{aligned}
  \mathbb{P}\big[T_j = t_j | R(t_j) \big] & = \frac{\mathbb{P}\big[T_j = t_j | T_j \geq t_j \big]}{\sum_{l \in R(t_j)} \ \mathbb{P}\big[T_l = t_l | T_l \geq t_j \big]} \\\\
  & = \frac{\lambda_j(t_j|\pmb{\mathrm{x_j}}, \beta)}{\sum_{l \in R(t_j)} \ \lambda_l(t_l|\pmb{\mathrm{x_l}}, \beta)} \\\\
  & = \frac{\lambda_0 (t_j, \alpha)\phi(\pmb{\mathrm{x_j}}, \beta)}{\sum_{l \in R(t_j)} \ \lambda_0 (t_j, \alpha)\phi(\pmb{\mathrm{x_l}}, \beta)} \\\\
  \mathbb{P}\big[T_j = t_j | R(t_j) \big] & = \frac{\phi(\pmb{\mathrm{x}_j}, \beta)}{\sum_{l \in R(t_j)} \phi(\pmb{\mathrm{x}_l}, \beta)}
\end{aligned}
(\#eq:contribpartiallikproof)
\end{equation}

## Partial likelihood function in PH models {-}

Based on equation \@ref(eq:contribpartiallik), one can derive the probability that all spells completed at $t_j$ ends in the $j^{\text{th}}$ failure time, such that:

\begin{equation}
\begin{aligned}
  \mathcal{L}_{p,\ t_j} & = \mathbb{P}\big[T_1 = t_j, \dots, T_{d_j} = t_j \ | \ R(t_j)\big] \\\\
  & = \Pi_{m \in D(t_j)} \ \mathbb{P}\big[T_m = t_j | R(t_j) \big] \\\\
  & = \Pi_{m \in D(t_j)} \ \frac{\phi(\pmb{\mathrm{x}_m}, \beta)}{\sum_{l \in R(t_j)} \phi(\pmb{\mathrm{x}_l}, \beta)} \\\\
  & = \Pi_{m \in D(t_j)} \ \phi(\pmb{\mathrm{x}_m}, \beta) \times \Pi_{m \in D(t_j)} \ \frac{1}{\sum_{l \in R(t_j)} \phi(\pmb{\mathrm{x}_l}, \beta)} \\\\
  \mathcal{L}_{p,\ t_j} & = \frac{\Pi_{m \in D(t_j)} \ \phi(\pmb{\mathrm{x}_m}, \beta)}{\Big[\sum_{l \in R(t_j)} \phi(\pmb{\mathrm{x}_l}, \beta)\Big]^{d_j}}
\end{aligned}
(\#eq:partlikproof)
\end{equation}

The joint probability over the $k$ ordered discrete failure times then becomes: 

\begin{equation}
\begin{aligned}
  \mathcal{L}_p & = \Pi_{j=1}^{k} \ \mathcal{L}_{p,\ t_j} \\\\
  \mathcal{L}_p & = \Pi_{j=1}^{k} \ \frac{\Pi_{m \in D(t_j)} \ \phi(\pmb{\mathrm{x}_m}, \beta)}{\Big[\sum_{l \in R(t_j)} \phi(\pmb{\mathrm{x}_l}, \beta)\Big]^{d_j}}
\end{aligned}
(\#eq:partlikproofbis)
\end{equation}
  


