---
title: "Portfolio, Churn & Customer Value"
author: "Hugo Cornet, Pierre-Emmanuel Diot, Guillaume Le Halper, Djawed Mancer"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography:
- biblio.bib
- packages.bib
biblio-style: apalike
link-citations: true
description: This research paper aims at modelling customer portfolio, churn and customer value.
---


# Abstract{-#abstract}

This paper is being realized as part of our last year in master's degree in Economics. It aims at studying the firm's most valuable asset: its customers. To that end, we adopt a quantitative approach based on a mix of Econometrics and Data Science techniques with a threefold purpose:

- Model customer *portfolio* as a set of customer segments.
- Predict and analyse customer *attrition*.
- Estimate the overall *value* of the firm's portfolio.

After having defined the subject's key concepts, we apply unsupervised classification algorithms and duration models to a [kaggle](https://www.kaggle.com/yeanzc/telco-customer-churn-ibm-dataset) dataset related to customers of a fictional telecommunications service provider (TSP). Once the customer segments identified and customer lifetime estimated, a new metric is proposed to compute customer *value* during their lifetime in the portfolio. The *value* of the portfolio is then calculated and various simulations are realised. 

**Keywords**: *customer portfolio management (CPM), churn, customer value, duration models, segmentation, telecom.* 

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 
  "bookdown", 
  "knitr", 
  "rmarkdown", 
  "FactoMineR", 
  "survival", 
  "flexsurv", 
  "randomForestSRC"
), "packages.bib")
```


